### ISSUE TITLE
Make the website responsive.

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4045]
I think the rough steps should be:
- [ ] Familiarise yourself with the website codebase
- [ ] Switch on the viewport to see how it responds generally
- [ ] Make a list of all the pages and different states (I can help with this)
- [ ] Split the list into ones that are going to need some design love and ones that are going to be straight-forward
- [ ] Do the straight-forward ones while @nicole designs the complex ones
- [ ] Do the complex ones.
- [ ] Merge the giant PR
- [ ] Wrap it as Android
