### ISSUE TITLE
Make side-exercise mentoring opt-in

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4375]
We had a community consultation on this issue [here](https://github.com/exercism/exercism/issues/4305), which outlined the problem we're trying to solve and lots of people's opinions on it. This is a tracking issue being implemented at https://github.com/exercism/website/pull/413

- [x] Change the mentoring model to allow for opting-in
- [x] Change the UI to have a button for request mentoring. 
- [x] Ensure that the UI doesn't remove the ability to see other solutions when mentoring has been requested.
- [x] Add a visual state to the exercises on the track page that show mentoring has been requested.
- [x] Ensure that all core exercises in mentoring mode stay in the queues with the correct date
- [x] Set all side-exercises to be optional-mentoring.
- [x] Set side-exercises that have already received mentoring to have mentoring_requested.
- [x] Add ability to cancel request for mentoring on solutions where no-one is mentoring.
- [x] Add ability to complete/publish side exercises
- [x] Add ability to complete/publish independent exercises
- [ ] Write an email to all users with exercises in the queues.
- [ ] Merge
- [ ] Deploy
- [ ] Send email.

**Comment by ErikSchierboom** [comment]
> Write an email to all users with exercises in the queues.

Does this imply that the existing side exercises will be removed from the queues? Just wondering.

**Comment by iHiD** [comment]
>Does this imply that the existing side exercises will be removed from the queues? Just wondering.

Yes it does.

**Comment by iHiD** [comment]
For clarity, to quote from an internal Slack message:

> As part of this migration, I am resetting all side exercises and independent mode exercises to *not* request mentoring. There are like 20k exercises in the queue atm, and they're never going to get seen. I intend to email everyone that's submitted a mentored-side or independent-mode since launch, which haven't been mentored, and tell them about this change and the fact that all their exercises have been reset and that they need to request things on them if they want to.

**Comment by ErikSchierboom** [comment]
Will there also be a limit on the number of side exercises one can request mentoring for? Or only have the first X side exercises of a student be displayed in the queue?

I think this is a wise decision by the way!

**Comment by iHiD** [comment]
So to quote my previous paragraph from the same internal conversation ;)

> - Side exercises in mentored mode no longer get mentoring by default. Instead, the user is encouraged to look at other solutions and learn from them. If they want mentoring then they can request it but they many only request it on **three** exercises at a time (per track).
> - In independent mode, there is no difference between core/side and someone can only request mentoring on **one** exercise at a time (per track).

**Comment by ErikSchierboom** [comment]
Love it!

**Comment by iHiD** [comment]
@ErikSchierboom: For reference/interest, in mentored mode, since v2 launch

```
Core solutions with iterations: 30,383
Which have been mentored: 19,684

Side solutions with iterations in v2: 27,387
Which have been mentored: 7,901
```

(cc @kytrinyx @nicolechalmers)

**Comment by ErikSchierboom** [comment]
Ah. That's more side exercises mentored  than I expected actually l.

**Comment by F3PiX** [comment]
Speaking for all mentors: THANKS! 

This one is finished, no? Close?
