### ISSUE TITLE
[Tracking] Re-enabling community comments

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4629]
This is the tracking issue for re-enabling community commenting. It is readonly. You can see the [WIP pull request here](https://github.com/exercism/website/pull/526).

- [x] Add ability for people to opt-in/out of comments on a per-solution basis in profile
- [x] Decouple reactions from comments
- [x] Change reactions to be more standardised emojis
- [x] [Fix formatting](https://github.com/exercism/exercism/issues/3859)
- [x] Implement commenting UI.
- [x] Add message to explain that comments are disabled if the user has chosen to do so.
- [x] Add ability for people to opt-in/out of comments on a per-solution basis on solution if comments are not present
- [x] Add ability for people to opt-in/out of comments on a per-solution basis on solution if comments are present
- [x] Add notification to all previous commenters when someone comments.
- [x] Add notification to solution user when someone comments.
- [x] Add global flag for default state of comments on/off.
- [x] Work out what default global setting should be and how that's communicated.
- [x] Add modal if global option is not set, which prompts to set it and also updates all solutions with that setting (only for users who have not yet published solutions). 
- [x] Add initial setting of global to `app/views/my/solutions/reflection/_publish_solution_form.html.haml`
- [x] Add counter caches
- [x] Add counter caching for num_comments
- [x] Add counter caching for num_stars
- [x] Add warning about purpose of comments
- [ ] Add ability to edit reflection.
- [ ] Add email to all previous commenters when someone comments.
- [ ] Add email to solution user when someone comments.

Closes https://github.com/exercism/exercism/issues/3859
Closes https://github.com/exercism/exercism/issues/4414
Closes https://github.com/exercism/exercism/issues/4156
Closes https://github.com/exercism/exercism/issues/4400

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
