### ISSUE TITLE
[Tracking] Send auto-emails to inactive mentors

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4713]
## Emails

- [ ] Send emails to a mentor who signs up and has not mentored a period of time later.
- [ ] Send emails to a mentor who has been active (0-4 solutions) and then ceases mentoring for a period of time.
- [ ] Send emails to a mentor who has been active (5-100 solutions) and then ceases mentoring for period of time.
- [ ] Send emails to a mentor who has been active (101+ solutions) and then ceases mentoring for a period of time.

("period of time" = 1.month?)

## Notes/feedback
- Forgot they signed up. _(send onboarding emails after signup?)_
- Good intentions but no time.
- Not sure they have the skills.
- Linked to above, want to finish track first. _(Quite common)_
- Didn't like algorithmic exercises. _(e.g. maths ones?)_
- Didn't feel that there was much feedback to give. _(I wonder if this means they don't see "bad" code as bad?)_ 
- Got stuck providing bio, wanting to do it properly and never getting round to it 
- Was just poking around - didn't really intend to mentor. _(rare)_

**Comment by ErikSchierboom** [comment]
Just a suggestion: maybe also ask why they haven't been mentoring? Is there something lacking on the website? Is it overwhelming? I'd be really curious for the reasons people don't mentor. Maybe we can learn a thing or two?

**Comment by iHiD** [comment]
Yep. That's exactly the plan! I'll ping you the pr when I've written it for
thoughts :)

**Comment by iHiD** [comment]
First one manually sent to people who have never mentored. For my reference and anyone else's interest:

**Spreadsheet**: `Mail merge: Never Mentored`
**Query:**
```ruby
pp User.where(id: TrackMentorship.where('created_at < ?', Time.now - 2.weeks).select(:user_id)).where.not(id: SolutionMentorship.select(:user_id)).map{|u|[u.email,u.handle,u.name]}
```

**Content:**
> Hi XXX,
> 
> A while back you signed up to mentor on Exercism but then never got started. That's something that's happening a lot (like 45% of the time) and I'm trying to work out why it is. My first step is to reach out to people like you to ask for your story.
> 
> Did you decide you weren't interested? Did the onboarding (or lack of it) suck? Did life get in the way? Still intending to but not got round to it? Something else? Would you mind taking thirty seconds and just dropping me a reply on what happened for you?
> 
> For clarity, I'm not nagging at all and I'm really grateful you were interesting in helping in the first place, but it would be super-helpful if I could just understand more. Equally, if you want to just ignore me, that's obviously fine too.
> 
> Thanks :)
> Jeremy Walker (iHiD)

**Comment by F3PiX** [comment]
Do you see patterns between tracks?

**Comment by iHiD** [comment]
Nice idea.

From the responses: I've not looked tbh, and also these people signed up over 12 months so would be painful to work that out.

I can however look at just the quantitive data though and see if we have different percentages not mentoring etc. I'll do that when I get some time.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
